// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKxW_Cv6ueUHBY5mY9ogqK_LJMqX2oVQ4',
    appId: '1:414108113530:android:ed8fa031f71307a3b679c3',
    messagingSenderId: '414108113530',
    projectId: 'receipt-book-95606',
    storageBucket: 'receipt-book-95606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGP5fiOgehQkozTgEN5AX1NBqrhh_-bDM',
    appId: '1:414108113530:ios:082deafcb5676fc3b679c3',
    messagingSenderId: '414108113530',
    projectId: 'receipt-book-95606',
    storageBucket: 'receipt-book-95606.firebasestorage.app',
    androidClientId: '414108113530-pc4pq3l45m9s56sqha4jkppq209e85cs.apps.googleusercontent.com',
    iosClientId: '414108113530-3nbt6sskrtd24kaalp5t1g54nvmpdnkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptBook',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArdH1cKIfRyNjrwsWvYKnR3zfsrhIqqbk',
    appId: '1:414108113530:web:113bafb9d44ddfeab679c3',
    messagingSenderId: '414108113530',
    projectId: 'receipt-book-95606',
    authDomain: 'receipt-book-95606.firebaseapp.com',
    storageBucket: 'receipt-book-95606.firebasestorage.app',
    measurementId: 'G-7Y1BFHR9NT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGP5fiOgehQkozTgEN5AX1NBqrhh_-bDM',
    appId: '1:414108113530:ios:082deafcb5676fc3b679c3',
    messagingSenderId: '414108113530',
    projectId: 'receipt-book-95606',
    storageBucket: 'receipt-book-95606.firebasestorage.app',
    androidClientId: '414108113530-pc4pq3l45m9s56sqha4jkppq209e85cs.apps.googleusercontent.com',
    iosClientId: '414108113530-3nbt6sskrtd24kaalp5t1g54nvmpdnkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArdH1cKIfRyNjrwsWvYKnR3zfsrhIqqbk',
    appId: '1:414108113530:web:b267b1e67827f17eb679c3',
    messagingSenderId: '414108113530',
    projectId: 'receipt-book-95606',
    authDomain: 'receipt-book-95606.firebaseapp.com',
    storageBucket: 'receipt-book-95606.firebasestorage.app',
    measurementId: 'G-D81D52F96M',
  );

}